return {
  foreground = '#c9d1d9',
  background = '#0d1117',
  cursor_bg = '#f78166',
  cursor_border = '#f78166',
  cursor_fg = '#0d1117',
  selection_bg = '#264f78',
  selection_fg = '#c9d1d9',

  ansi = {
    '#484f58',
    '#f85149',
    '#3fb950',
    '#d29922',
    '#58a6ff',
    '#bc8cff',
    '#39d353',
    '#b1bac4',
  },

  brights = {
    '#6e7681',
    '#ff7b72',
    '#56d364',
    '#e3b341',
    '#79c0ff',
    '#d2a8ff',
    '#56d364',
    '#f0f6fc',
  },

  tab_bar = {
    background = '#0d1117',
    active_tab = {
      bg_color = '#21262d',
      fg_color = '#c9d1d9',
      intensity = 'Normal',
      underline = 'None',
      italic = false,
      strikethrough = false,
    },
    inactive_tab = {
      bg_color = '#0d1117',
      fg_color = '#8b949e',
      intensity = 'Normal',
      underline = 'None',
      italic = false,
      strikethrough = false,
    },
    inactive_tab_hover = {
      bg_color = '#161b22',
      fg_color = '#c9d1d9',
      intensity = 'Normal',
      underline = 'None',
      italic = false,
      strikethrough = false,
    },
    new_tab = {
      bg_color = '#0d1117',
      fg_color = '#8b949e',
      intensity = 'Normal',
      underline = 'None',
      italic = false,
      strikethrough = false,
    },
    new_tab_hover = {
      bg_color = '#161b22',
      fg_color = '#c9d1d9',
      intensity = 'Normal',
      underline = 'None',
      italic = false,
      strikethrough = false,
    },
  },
} 